version: '3'

services:
  # Definition pour MySQL au lieu de PostgreSQL
  database:
    image: mysql:8.0.29 # Ou toute autre version de MySQL appropriée
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-app} # Nom de la base de données
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-Codemaster69} # Mot de passe pour l'utilisateur root
      MYSQL_USER: ${MYSQL_USER:-app} # Nom de l'utilisateur de la base de données
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-Codemaster69} # Mot de passe pour l'utilisateur de la base de données
      # MAILER_DSN n'est généralement pas une configuration liée à MySQL. Assurez-vous qu'elle est placée correctement dans votre configuration.
    volumes:
      - database_data:/var/lib/mysql:rw
      # Comme pour PostgreSQL, vous pouvez utiliser un chemin sur l'hôte si vous préférez.
